

#########################################################################
#
# 
#

sensor:
  - platform: duty_time
    id: led_lifetime_use
    name: "LED Lifetime Use"
    sensor: led_state
    update_interval: 10s


  - platform: template
    id: colour_temp_value
    name: "Colour Temperature Value"
    lambda: |-
      return id(colour_temp).current_value;
    update_interval: 1s  # Adjust as needed
    

binary_sensor:
  - platform: template
    name: "LED State"
    id: led_state
    lambda: |-
      return id(colour_temp_value).state > 0.1
#    internal: true
