

#########################################################################
#
# 
#

sensor:
#  - platform: duty_time
#    id: led_lifetime_use
#    name: "LED Lifetime Use"
#    sensor: led_state
#    update_interval: 10s


  - platform: template
    id: colour_temp_value
    name: "Colour Temperature Value"
    lambda: |-
      // Assuming you have a way to read the PWM output value; otherwise, this is a placeholder.
      return id(colour_temp).state;  // Replace with the actual method to read the PWM value if needed
    update_interval: 1s

    

#binary_sensor:
#  - platform: template
#    name: "LED State"
#    id: led_state
#    lambda: |-
#     return id(colour_temp_value).state > 0.1
#    internal: true
