#####################################################################
#
# Combined with web_server settings in /common/base-configuration to
# define a network information group
#

web_server:
  version: 3
  sorting_groups:
    - id: group_light_controls
      name: "Light Controls"
      sorting_weight: -20

#########################################################################
#
# Configure the onboard RGB LED of the ESP32-S3 board
#

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812x
    pin: 48
    num_leds: 1
    name: "Onboard RGB LED"
    id: onboard_led
    icon: 'mdi:led-on'
    effects:
      - strobe:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
    web_server:
      sorting_group_id: group_light_controls
      sorting_weight: 1

#########################################################################
