   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:

   # Default name
  name: "garage-controller"
   # Default friendly name
  friendly_name: "Garage"
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "GPO 2"   


   # BME 280 / BME680 Sensor
   #
   # Location of BME280/680 Sensor #1. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor1_location: ""
   # Location of BME280/680 Sensor #2. Used to prefix sensor if there are two. Leave empty if only 1. Add a " - " to the end of each entry if used.
  bme_sensor2_location: ""
   # Calibrate the outpute of the temperature sensor(s).
  temperature_1_offset: "0.0"
  temperature_2_offset: "0.0"
   # Calibrate the outpute of the pressure sensor(s).
  pressure_1_offset: "0.0"
  pressure_2_offset: "0.0"
   # Calibrate the outpute of the humidity sensor(s).
  humidity_1_offset: "0.0"
  humidity_2_offset: "0.0"

#########################################################################
packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/garage-controller.yaml]
    refresh: 5s # optional

esphome:
  name_add_mac_suffix: false

esp32:
  # Board Type = esp32-s3
  board: esp32dev
  framework:
    type: arduino
  flash_size: 4MB

#########################################################################
