substitutions:
  name: "gpo-ups-network"
  friendly_name: "UPS - Network Rack"
  device_description: "Athom Plug v3 - Phase C / GPO 1 - Network Rack Devices"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: "Network Rack"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO1 = Phase C, GPO2 = Phase A, GPO3 = Phase B)
  power_circuit: "GPO 2"  
  relay_restore_mode: ALWAYS_ON  

esphome:
  name: "${name}"
  name_add_mac_suffix: false

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v3.yaml]
    refresh: 0d # optional
