substitutions:
  name: "gpo-fireplace"
  friendly_name: "GPO - Fireplace"
  device_description: "Arlec PC191HA v2 - Monitoring the power & energy of fireplace powerpoint"
  location: "Living Room"
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO1 = Phase C, GPO2 = Phase A, GPO3 = Phase B)  
  power_circuit: "GPO 3"
   # Restore the relay (GPO switch) upon reboot to state:
  relay_restore_mode: ALWAYS_ON
   #
  disable_entities: "false"
   # HLW8012 Power Monitoring Chip
   # https://community.home-assistant.io/t/esphome-install-does-not-update-firmware/544026/9?u=mahko_mahko
   #
  voltage_divider: "762.3087621696801"
  current_resistor: "0.001076938663025147"
  current_multiply: "0.4320333227108756"
   #
  watts_factor: "1.0"

esphome:
  name_add_mac_suffix: False

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/arlec-pc191ha-plug-v2.yaml]
    refresh: 5s