substitutions:
  name: "gpo-clothes-dryer"
  friendly_name: "Clothes Dryer"
  device_description: "Athom Plug v2 - Phase B / GPO 3 - Clothes Dryer"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: "Patio"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "GPO 3"    
  #  
  relay_restore_mode: RESTORE_DEFAULT_ON
  # Set the update interval for power, current, energy sensors to update

esphome:
  name: "${name}"
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v2.yaml]
    refresh: 0d # optional
