substitutions:
  name: "plug-plasma-ball"
  friendly_name: "Plug - Plasma Ball"
  device_description: "Arlec PC191HA v2 - Monitoring & controlling Plasma Ball"
  location: "Bedroom - Master"
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO1 = Phase C, GPO2 = Phase A, GPO3 = Phase B)  
  power_circuit: "GPO 2"  # Study GPO next to printer
     # Restore the relay (GPO switch) upon reboot to state:
  relay_restore_mode: RESTORE_DEFAULT_OFF
   #  
  disable_entities: "false"
   # HLW8012 Power Monitoring Chip
   # https://community.home-assistant.io/t/esphome-install-does-not-update-firmware/544026/9?u=mahko_mahko
   #
  voltage_divider: "715.6720536066221"
  current_resistor: "0.0010719599107004646"
  current_multiply: "0.4226813425475587"
   #
  watts_factor: "1.148851519419724"

esphome:
  name_add_mac_suffix: False

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/arlec-pc191ha-plug-v2.yaml
  import_full_config: false

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/arlec-pc191ha-plug-v2.yaml]
    refresh: 5s

#########################################################################