sensor:

#######################################
#
#  General UPS Monitoring Info
#

#   String containing UPS model, eg: Smart-UPS 1000
  - platform: snmp
    unique_id: ups_study_model
    name: UPS - Study - Model
    host: 10.0.0.23
    baseoid: 1.3.6.1.4.1.318.1.1.1.1.1.1.0
    accept_errors: true

#   String containing UPS Name
#  - platform: snmp
#    unique_id: ups_study_name
#    name: UPS - Study - Name
#    host: 10.0.0.23
#    baseoid: 1.3.6.1.4.1.318.1.1.1.1.1.2.0
#    accept_errors: true

#######################################
#
#  Battery Information
#

#   Battery Replacement - If result = 2 then battery needs replacing (1 = ok)
  - platform: snmp
    unique_id: ups_study_battery_status
    name: UPS - Study - Battery Status
    host: 10.0.0.23
    baseoid: 1.3.6.1.4.1.318.1.1.1.2.2.4.0
    accept_errors: true
    value_template: >-
      {%if value == '1' %}
        Good
      {% elif value == '2' %}
        Failed
      {% endif %}


#   The date when the UPS system's batteries were last replaced in mm/dd/yy format.
#  - platform: snmp
#    unique_id: ups_study_battery_last_replaced
#    name: UPS - Study - Battery Last Replaced
#    host: 10.0.0.23
#    baseoid: 1.3.6.1.4.1.318.1.1.1.2.1.3.0
#    accept_errors: true


#######################################
#
#  UPS Input
#

#   String containing reason for last transfer to battery power
  - platform: snmp
    unique_id: ups_study_last_transfer_reason
    name: UPS - Study - Last Transfer Reason
    host: 10.0.0.23
    baseoid: 1.3.6.1.4.1.318.1.1.1.3.2.5.0
    accept_errors: true
    value_template: >-
      {%if value == '1' %}
        No events
      {% elif value == '2' %}
        High line voltage
      {% elif value == '3' %}
        Brownout
      {% elif value == '4' %}
        Loss of mains power
      {% elif value == '5' %}
        Small temporary power drop
      {% elif value == '6' %}
        Large temporary power drop
      {% elif value == '7' %}
        Small spike
      {% elif value == '8' %}
        Large spike
      {% elif value == '9' %}
        UPS self test
      {% elif value == '10' %}
        Excessive input voltage fluctuation
      {% endif %}


#######################################
#
#  UPS Output
#

#   Output frequency from the UPS in Hz
#  - platform: snmp
#    unique_id: ups_study_output_frequency
#    name: UPS - Study - Output Frequency
#    host: 10.0.0.23
#    baseoid: 1.3.6.1.4.1.318.1.1.1.4.2.2.0
#    accept_errors: true
#    unit_of_measurement: 'Hz'

#######################################
#
#  UPS Diagnostics
#

#  - platform: snmp
#    unique_id: ups_study_last_self_test_date
#    name: UPS - Study - Last Self Test Date
#    host: 10.0.0.23
#    baseoid: 1.3.6.1.4.1.318.1.1.1.7.2.4.0
#    accept_errors: true

#   Whether SNMP agent is communicating with UPS device 1 = yes, 2 = no
  - platform: snmp
    unique_id: ups_study_snmp_status
    name: UPS - Study - SNMP Status
    host: 10.0.0.23
    baseoid: 1.3.6.1.4.1.318.1.1.1.8.1.0
    accept_errors: true
    value_template: >-
      {%if value == '1' %}
        Online
      {% elif value == '2' %}
        Offline
      {% endif %}

  - platform: snmp
    unique_id: ups_study_state
    name: UPS - Study - State
    host: 10.0.0.23
    baseoid: 1.3.6.1.4.1.318.1.1.1.4.1.1.0
    accept_errors: true
    value_template: >-
      {%if value == '1' %}
        Unknown
      {% elif value == '2' %}
        On Grid
      {% elif value == '3' %}
        On Battery
      {% elif value == '4' %}
        On Smart Boost
      {% elif value == '5' %}
        Timed Sleeping
      {% elif value == '6' %}
        Software Bypass
      {% elif value == '7' %}
        Off
      {% elif value == '8' %}
        Rebooting
      {% elif value == '9' %}
        Switched Bypass
      {% elif value == '10' %}
        Hardware Failure Bypass
      {% elif value == '11' %}
        Sleeping Until Power Returns
      {% elif value == '12' %}
        On Smart Trim
      {% endif %}


##########################################################################################

homeassistant:
  customize:

    sensor.ups_study_state:
      device_class: connectivity
      friendly_name: UPS - Study - State


##########################################################################################

template:

    # Converts the Self Test Date from MM/DD/YY to DD/MM/YYYY format
  - sensor:
    - name: UPS - Study - Battery Replaced
      unique_id: ups_study_battery_replaced
      icon: mdi:clock-start      
      state: >-
        {% set date_parts = states('sensor.ups_study_battery_date').split('/') %}
        {% set year = '20' ~ date_parts[2] %}
        {{ strptime(states('sensor.ups_study_battery_date'), '%m/%d/%y').strftime('%d/%m/') ~ year }}


    # Converts the Self Test Date from YYYY/MM/DD to DD/MM/YYYY format
  - sensor:
    - name: "UPS - Study - Self Test Date DMY"
      unique_id: ups_study_self_test_date_dmy
      icon: mdi:clock-start
      state: >-
        {% set date_value = states('sensor.ups_study_self_test_date') %}
        {% if date_value %}
          {% set parsed_date = strptime(date_value, '%m/%d/%Y', true) %}
          {% if parsed_date is not none %}
            {{ parsed_date.strftime('%d/%m/%Y') }}
          {% else %}
            "Invalid Date Format"
          {% endif %}
        {% else %}
          "No Date Available"
        {% endif %}


    # Calculates the age of the UPS battery
  - sensor:
    - name: "UPS - Study - Battery Age"
      unique_id: ups_study_battery_age
      unit_of_measurement: "years"
      state: >
        {% set battery_replaced = strptime(states('sensor.ups_study_battery_date'), '%m/%d/%y') %}
        {% set today = states('sensor.date') %}
        {% set today_year, today_month, _ = today.split('-') %}
        {% set battery_year, battery_month, _ = battery_replaced.strftime('%Y-%m-%d').split('-') %}
        {% set years = (today_year | int) - (battery_year | int) %}
        {% set months = (today_month | int) - (battery_month | int) %}
        {% if months < 0 %}
          {% set years = years - 1 %}
          {% set months = months + 12 %}
        {% endif %}
        {{ years + (months / 12) | round(2) }}


##########################################################################################