
substitutions:
  name: gpo-bedroom-xxxx
  friendly_name: "GPO - Bedroom - XXXX"
  device_description: "Athom Plug v3 - Phase X / GPO X - Monitoring the power & energy of bedroom powerpoint"  
  location: "Bedroom - XXXX"  
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "GPO X"  

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v3.yaml]
    refresh: 5s # optional

esphome:
  name: "${name}"
  name_add_mac_suffix: false
