esphome:
  name: living_room_light

wifi:
  ssid: "your_ssid"
  password: "your_password"

logger:

_pi:
  platform: gpio
  pin : 16
  id: output_component

light:
  - platform: monochromatic
    name: "Living Room Light"
    output: output_component
