#########################################################################
#
# Substitutions
#
substitutions:
   # Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "true"

########################## End of Substitutions #########################
#
# Configuration to add WiFi network connection to ESP Devices
#

wifi:
  # WiFi credentials
  ssid: !secret wifi_ssid
  password: !secret wifi_password
   # This spawns an AP with the device name and mac address with no password.
  ap: {}
   # Allow rapid re-connection to previously connect WiFi SSID, skipping scan of all SSID
  fast_connect: "${wifi_fast_connect}"
   # Define dns domain / suffix to add to hostname
  domain: "${dns_domain}"

 # Define a static IP address (optional)
#  manual_ip:
#    static_ip: ${network_ip}
#    gateway: ${network_gateway}
#    subnet: ${network_subnet}
#    dns1: ${dns_server1}
#    dns2: ${dns_server2}

   # Only works for WiFi connected devices 
captive_portal:

##########################################################################
#
# Sensors - WiFi Specific
#

sensor:

   # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal dB"
    update_interval: 150s
    icon: mdi:wifi-strength-2
    entity_category: "diagnostic"
    web_server_sorting_weight: 45
    internal: true

   # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    id: wifi_strength
    icon: mdi:wifi-arrow-up-down
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
    web_server_sorting_weight: 44

##########################################################################
#
# Text Sensors - WiFi Specific
#

text_sensor:

   # Creates sensor for tracking the WiFi IP address
  - platform: wifi_info
    ip_address:
      name: 'WiFi IP Address'
      icon: mdi:ip-network
      entity_category: diagnostic
      web_server_sorting_weight: 41

   # Creates sensor for tracking the WiFi IP MAC address
    mac_address:
      name: 'WiFi MAC Address'
      icon: mdi:network-pos
      entity_category: diagnostic
      web_server_sorting_weight: 42

   # Defines the WiFi SSID network to connect to
    ssid:
      name: 'WiFi SSID'
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
      web_server_sorting_weight: 43

##########################################################################
