#########################################################################
#
# Configuration to add WiFi network connection to ESP Devices
#

wifi:
  # WiFi credentials
  ssid: !secret wifi_ssid
  password: !secret wifi_password
   # This spawns an AP with the device name and mac address with no password.
  ap: {}
   # Allow rapid re-connection to previously connect WiFi SSID, skipping scan of all SSID
  fast_connect: "${wifi_fast_connect}"
   # Define dns domain / suffix to add to hostname
  domain: "${dns_domain}"

   # Only works for WiFi connected devices 
captive_portal:

##########################################################################
#
# Sensors - WiFi Specific
#

sensor:

   # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal
    id: wifi_signal_db
    name: "WiFi Signal dB"
    update_interval: 150s
    entity_category: "diagnostic"
    internal: true

   # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Strength"
    id: wifi_strength
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

##########################################################################
#
# Text Sensors - WiFi Specific
#

text_sensor:

   # Creates sensor for tracking the WiFi IP address
  - platform: wifi_info
    ip_address:
      name: 'WiFi IP Address'
      icon: mdi:wifi
      entity_category: diagnostic

   # Defines the WiFi SSID network to connect to
    ssid:
      name: 'WiFi SSID'
      icon: mdi:wifi-strength-2
      entity_category: diagnostic

   # Creates sensor for tracking the WiFi IP MAC address
    mac_address:
      name: 'WiFi MAC Address'
      entity_category: diagnostic

##########################################################################
