#########################################################################
#
# Air Quality monitoring using ESP32 chipset and MQ7, MQ7 and MQ135 sensor(s)
# See: https://tristam.ie/2023/158/
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name  
  name: "air-quality-monitor"
   # Default friendly name 
  friendly_name: "Air Quality Monitor"
   # Description as appears in ESPHome & top of webserver page
  device_description: "DIY - Air Quality Monitor (CO2, Flammable & Harmful Gas)"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc    
  location: ""
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "TBA"  
   # Project Name
  project_name: "DIY.Air Quality Monitor"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "0.1.0"

   # If true, entity should not be added to Home Assistant frontend, without the user manually enabling it.
  disable_by_default: "false"

   # I2C PINS - Used for sensors on Bus A
  sda_pin: "GPIO4"      # For WeMOS D1 Mini
  scl_pin: "GPIO5"      # For WeMOS D1 Mini
  
########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device. 
# Must be in the local devices configuration file.
#

#esp8266:
#  board: d1_mini

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/air-quality-monitor.yaml@main
  import_full_config: false

packages:
  base-config:      !include common/base-configuration.yaml
  wifi-config:      !include common/network-wifi.yaml

#########################################################################

i2c:
  sda: ${sda_pin}
  scl: ${scl_pin}
  scan: true
  id: db_busa
  
ads1115:
  #  continuous_mode : on
 - address: 0x48
   id: ads1115_48
   continuous_mode: on

sensor:
# MQ2 - ensor is suitable for detecting LPG, i-butane, propane, methane ,alcohol, Hydrogen, smoke

#  MQ7 - Carbon Monoxide (CO) sensor suitable for sensing CO concentrations in the air. It can detect CO-gas concentrations anywhere from 20 to 2000ppm.
  - name: "CO2 Sensor (MQ7)"
    id: co2_sensor #ads1115_48_a1
    ads1115_id: ads1115_48
    multiplexer: 'A1_GND'
    gain: 6.144
    platform: ads1115
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      lambda: return (x/3.3 *100); 
    unit_of_measurement: "%"
    icon: "mdi:molecule-co2"
    web_server:
      sorting_group_id: group_air_quality_sensors
      sorting_weight: 1

# MQ5 - suitable for detecting H2, LPG, CH4, CO, Alcohol
  - name: "Flammable Gas Sensor (MQ5)"
    id: flammable_gas_sensor #ads1115_48_a0
    ads1115_id: ads1115_48
    multiplexer: 'A0_GND'
    gain: 6.144
    platform: ads1115
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      lambda: return (x/3.3 *100);    
    unit_of_measurement: "%"
    icon: "mdi:fire"
    web_server:
      sorting_group_id: group_air_quality_sensors
      sorting_weight: 2

# Suitable for ammonia, aromatic compounds, sulfur, benzene vapor, smoke and other gases harmful gas detection. Gas-sensitive element test concentration range: 10 to 1000ppm
  - name: "Harmful Gas Sensor (MQ135)"
    id: harmful_gas_sensor #ads1115_48_a2
    ads1115_id: ads1115_48
    multiplexer: 'A2_GND'
    gain: 6.144
    platform: ads1115
    accuracy_decimals: 2
    update_interval: 30s
    filters:
      lambda: return (x/3.3 *100);        
    unit_of_measurement: "%"    
    icon: "mdi:skull-crossbones"
    web_server:
      sorting_group_id: group_air_quality_sensors
      sorting_weight: 3
      
#########################################################################
#
# Web_server v3 Sort Groups - These substitutes are applied to overwrite the default ones supplied by the 
# sensor specific template file, in this case the /sensors/hc-sr04-ultrasonic.yaml file.
#

web_server:
  sorting_groups:
    - id: group_air_quality_sensors
      name: "Air Quality Sensors"
      sorting_weight: -38
