#########################################################################
#
# Device configuration for Athom Wall Switch, with neutral (ESP8285)
#

##########################################################################
# VERSION UPATES:
#
# v0.1.0 - Upate to use Roving Ronin base configurations
#

substitutions:
  # Default name
  name: "light-switch-4gang"
  # Default friendly name
  friendly_name: "Light Switch - 4 Gang"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Athom  - Light Switch 4 Gang"
  # Project Name
  project_name: "Athom Technology.Wall Switch 4 Gang"
  # Projection version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "v0.1.0"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  location: ""
  # The phase in the home power supply, upon which this device is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)  
  power_circuit: "TBA"  
  # Restore the relay (GPO switch) upon reboot to state:
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  light4_restore_mode: RESTORE_DEFAULT_OFF

  button1_assignment: "Button 1"
  button2_assignment: "Button 2"
  button3_assignment: "Button 3"
  button4_assignment: "Button 4"
  
########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#
esp8266:
  board: esp8285
  restore_from_flash: true


#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/athom-wall-switch-4gang.yaml.yaml@main
  import_full_config: false


packages:
  base-config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/base-configuration.yaml]
    refresh: 1h
    
  network_config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/network-wifi.yaml]
    refresh: 1h

  webserver_groups:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/webserver-groups.yaml]
    refresh: 5s


#####################################################################
#
# Combined with web_server settings in /common/base-configuration to
# define a network information group
#

web_server:
  sorting_groups:
    
    - id: group_light_switches
      name: "Light Switches"
      sorting_weight: -30


#####################################################################
#
#
#
esphome:
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(light1).turn_off();
                      id(light2).turn_off();
                      id(light3).turn_off();
                      id(light4).turn_off();
                      break;
                            }
              case 2:{
                      id(light1).turn_on();
                      id(light2).turn_on();
                      id(light3).turn_on();
                      id(light4).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }

logger:
  baud_rate: 115200


#########################################################################
#
# Globals to save values to NVS RAM
#

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "3"

#########################################################################
#
# Select action to set default power on state
#

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    icon: "mdi:electric-switch"
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;
    entity_category:  config


#########################################################################
#
# Binary Sensors
#
binary_sensor:

  # Touch Button 1
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
    name: ${button1_assignment}
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  # Touch Button 2
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: ${button2_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

  # Touch Button 3  
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: ${button3_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

  # Touch Button 4
  - platform: gpio
    pin:
      inverted: true
      number: GPIO16
    name: ${button4_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light4


##########################################################################
#
# Relays
#
output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1

  - platform: gpio
    pin: GPIO4
    id: relay2

  - platform: gpio
    pin: GPIO15
    id: relay3

  - platform: gpio
    pin: GPIO14
    id: relay4


##########################################################################
#
# Lights
#
light:

  # Relays
  - platform: binary
    name: "Light1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}
    icon: "mdi:lightbulb-outline"
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 1
      
  - platform: binary
    name: "Light2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    icon: "mdi:lightbulb-outline"
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 2
    
  - platform: binary
    name: "Light3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    icon: "mdi:lightbulb-outline"
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 3
    
  - platform: binary
    name: "Light4"
    id: light4
    output: relay4
    restore_mode: ${light4_restore_mode}
    icon: "mdi:lightbulb-outline"
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 4


  # ESP PCB Light
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true
    icon: "mdi:lightbulb-outline"
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 5


##########################################################################

