#########################################################################
#
# Device configuration for Athom Wall Switch, with neutral (ESP8285)
#

##########################################################################
# VERSION UPATES:
#
# v0.1.0 - Upate to use Roving Ronin base configurations
#

substitutions:
  # Default name
  name: "athom-4gang-switch"
  # Default friendly name
  friendly_name: "4Gang Switch"
  # Allows ESP device to be automatically linked to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: ""
  # Description as appears in ESPHome & top of webserver page
  device_description: "athom 4gang switch"
  # Project Name
  project_name: "Athom Technology.4Gang Switch"
  # Projection version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "v0.1.0"
   # Restore the relay (GPO switch) upon reboot to state:
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  light4_restore_mode: RESTORE_DEFAULT_OFF

  button1_assignment: "Button 1"
  button2_assignment: "Button 2"
  button3_assignment: "Button 3"
  button4_assignment: "Button 4"
  
########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#
esp8266:
  board: esp8285
  restore_from_flash: true


#########################################################################
#
# Remote Packages to be utilised
#
dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/athom-sw04.yaml@main
  import_full_config: false

packages:
  base-config:         !include common/base-configuration.yaml
  wifi-config:         !include common/network-wifi.yaml


#####################################################################
#
#
#
esphome:
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(light1).turn_off();
                      id(light2).turn_off();
                      id(light3).turn_off();
                      id(light4).turn_off();
                      break;
                            }
              case 2:{
                      id(light1).turn_on();
                      id(light2).turn_on();
                      id(light3).turn_on();
                      id(light4).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }

logger:
  baud_rate: 115200


#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-sw04.yaml

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "3"

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;


#########################################################################
#
# Binary Sensors
#
binary_sensor:

  # Touch Button 1
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
    name: ${button1_assignment}
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  # Touch Button 2
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
    name: ${button2_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

  # Touch Button 3  
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
    name: ${button3_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

  # Touch Button 4
  - platform: gpio
    pin:
      inverted: true
      number: GPIO16
    name: ${button4_assignment}
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light4


##########################################################################
#
# Relays
#
output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1

  - platform: gpio
    pin: GPIO4
    id: relay2

  - platform: gpio
    pin: GPIO15
    id: relay3

  - platform: gpio
    pin: GPIO14
    id: relay4


##########################################################################
#
# Lights
#

light:
  # ESP PCB Light
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "Light1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}
    
  - platform: binary
    name: "Light2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    
  - platform: binary
    name: "Light3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    
  - platform: binary
    name: "Light4"
    id: light4
    output: relay4
    restore_mode: ${light4_restore_mode}


##########################################################################
