#########################################################################
#
# Device configuration for Athom Smart Plug v2 (ESP8285)
# providing power and energy monitoring sensors.
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name
  name: "athom-smart-plug-v2-no-relay"
   # Default friendly name 
  friendly_name: "Smart Plug v2 - No Relay"
   # Description as appears in ESPHome & top of webserver page
  device_description: "Athom Plug v2 - Smart Plug (ESP8285) without relay"
   # Project Name
  project_name: "Athom Technology.Smart Plug v2 without relay"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "1.0.0"
   # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "DEBUG"

   # DO NOT CHANGE THESE SETTINGS. They are specific to the Plug Hardware Version, as defined by Athom.
  power_button_pin:   "5"
  gpo_status_led_pin: "GPIO13"

########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#

esp8266:
  board: esp8285
  restore_from_flash: true

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/athom-smart-plug-no-relay.yaml@main
  import_full_config: false

packages:
  base-config:         !include common/base-configuration.yaml
  wifi-config:         !include common/network-wifi.yaml
  athom-power-sensors: !include sensors/athom-power-plug-no-relay.yaml

#####################################################################
#
# Define the COMs Port
#

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

#####################################################################
