#########################################################################
#
# Device configuration for Athom Wall Switch, with neutral (ESP8285)
#

##########################################################################
# VERSION UPATES:
#
# v0.1.0 - Upate to use Roving Ronin base configurations
#

substitutions:
  # Default name
  name: "switch-3gang"
  # Default friendly name
  friendly_name: "Switch - 3 Gang"
  # Description as appears in ESPHome & top of webserver page
  device_description: "Athom  - Light Switch 3 Gang"
  # Project Name
  project_name: "Athom Technology.Light Switch 3 Gang"
  # Projection version denotes the release version of the yaml file, allowing checking of deployed vs latest version
  project_version: "v0.1.0"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc  
  location: ""
  # The phase in the home power supply, upon which this device is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)  
  power_circuit: "Lights"
  # Restore the relay (GPO switch) upon reboot to state:
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  # Button Label Names
  button1_assignment: "Button 1"
  button2_assignment: "Button 2"
  button3_assignment: "Button 3"
  button4_assignment: "Button 4"


########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#

esp8266:
  board: esp8285
  restore_from_flash: true

logger:
  baud_rate: 115200

preferences:
   # Enable to allow storing of 'Read Total' between reboots and flashing.
  flash_write_interval: 30min
  

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/athom-wall-switch-4gang.yaml.yaml@main
  import_full_config: false


packages:
  base-config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/base-configuration.yaml]
    refresh: 1h
    
  network_config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/network-wifi.yaml]
    refresh: 1h

  webserver_groups:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/webserver-groups.yaml]
    refresh: 5s

#####################################################################
#
# External Components
#

# Dentra Components - Adds 'Platform - Energy Statistics'
# https://github.com/Roving-Ronin/myHomeAssistant/tree/main/components/energy_statistics

external_components:
  - source:
      type: git
      url: https://github.com/roving-ronin/myhomeassistant/
      ref: main
    refresh: 1h
    components: [ usage_tracker ]


#####################################################################
#
# Combined with web_server settings in /common/base-configuration to
# define a network information group
#

web_server:
  sorting_groups:
    
    - id: group_light_switches
      name: "Light Switches"
      sorting_weight: -30

    - id: group_light_usage
      name: "Light Statistics"
      sorting_weight: -20


#####################################################################
#
#
#

esphome:
  on_boot:
    - priority: 600
      then:
        - select.set_index:
            id: power_mode
            index: !lambda |-
                    return id(restore_mode)-1;
        - lambda: |-
              switch(id(restore_mode))
              {
              case 1:{
                      id(light1).turn_off();
                      id(light2).turn_off();
                      id(light3).turn_off();
                      break;
                            }
              case 2:{
                      id(light1).turn_on();
                      id(light2).turn_on();
                      id(light3).turn_on();
                      break;
                            }
              default:{
                      break;
                            }
              }

#########################################################################
#
# Globals to save values to NVS RAM
#

globals:
  - id: restore_mode
    type: int
    restore_value: yes
    initial_value: "3"


#########################################################################
#
# Select action to set default power on state
#

select:
  - platform: template
    name: "Power On State"
    id: "power_mode"
    optimistic: true
    options:
      - Always Off
      - Always On
      - Restore Power Off State
    on_value:
      then:
        - lambda: |-
            id(restore_mode)=i+1;



#########################################################################
#
# Binary Sensors
#

binary_sensor:

  # Touch Button 1
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
      mode:
        input: true
        pullup: true
    name: ${button1_assignment}
    id: button1
    icon: 'mdi:gesture-tap-button'
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset
    internal: false            # TRUE  

  # Touch Button 2
  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
      mode:
        input: true
        pullup: true
    name: ${button2_assignment}
    id: button2
    icon: 'mdi:gesture-tap-button'
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2
    internal: false            # TRUE  


  # Touch Button 3
  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: ${button3_assignment}
    id: button3
    icon: 'mdi:gesture-tap-button'
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3
    internal: false            # TRUE  


    # Binary sensor that tracks of the Light (id: downlight) is ON or OFF.
    # This is used by the usage_tracker as its source sensor.
  - platform: template
    name: "Light 1 - State"
    id: light1_state
    lambda: |-
      return id(light1).current_values.is_on();
    internal: true

    # Binary sensor that tracks of the Light (id: downlight) is ON or OFF.
    # This is used by the usage_tracker as its source sensor.
  - platform: template
    name: "Light 2 - State"
    id: light2_state
    lambda: |-
      return id(light2).current_values.is_on();
    internal: true

    # Binary sensor that tracks of the Light (id: downlight) is ON or OFF.
    # This is used by the usage_tracker as its source sensor.
  - platform: template
    name: "Light 3 - State"
    id: light3_state
    lambda: |-
      return id(light3).current_values.is_on();
    internal: true


##########################################################################
#
# Relays
#

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1

  - platform: gpio
    pin: GPIO4
    id: relay2

  - platform: gpio
    pin: GPIO15
    id: relay3

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO16
    inverted: true
    id: button_led1
    
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: button_led2
    
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: button_led3


##########################################################################
#
# Lights
#

light:

  # Relays
  - platform: binary
    name: "Light 1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

  - platform: binary
    name: "Light 2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2

  - platform: binary
    name: "Light 3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    on_turn_on:
      - light.turn_on: led3
    on_turn_off:
      - light.turn_off: led3


  - platform: status_led
    name: "Status LED"
    icon: 'mdi:wifi-alert'
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 4


############################

  # Button LEDs
  - platform: monochromatic
    name: "Backlight 1"
    icon: 'mdi:led-on'
    disabled_by_default: true
    id: led1
    output: button_led1
    default_transition_length: 500ms
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 


  - platform: monochromatic
    name: "Backlight 2"
    icon: 'mdi:led-on'
    disabled_by_default: true
    id: led2
    output: button_led2
    default_transition_length: 500ms
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 

      
  - platform: monochromatic
    name: "Backlight 3"
    icon: 'mdi:led-on'
    disabled_by_default: true
    id: led3
    output: button_led3
    default_transition_length: 500ms
    web_server:
      sorting_group_id: group_light_switches
      sorting_weight: 

