#########################################################################
#
# Device configuration for Athom Smart Plug v2 (ESP8285)
# providing power and energy monitoring sensors.
#


##########################################################################
# VERSION UPATES:
#
# v1.7.0 - Upate to Dentra v2 energy_statistics with publish yesterday = 0
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name
  name: "athom-smart-plug-v2-no-relay"
   # Default friendly name 
  friendly_name: "Smart Plug - No Relay"
   # Description as appears in ESPHome & top of webserver page
  device_description: "Athom Plug (No Relay) - Smart Plug (ESP8285)"
   # Project Name
  project_name: "Athom Technology.Smart Plug (No Relay)"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "1.7.1"
   # Define logging level: NONE, ERROR, WARN, INFO, DEBUG (Default), VERBOSE, VERY_VERBOSE
  log_level: "NONE"

   # DO NOT CHANGE THESE SETTINGS. They are specific to the Plug Hardware Version, as defined by Athom.
  power_button_pin:   "5"
  gpo_status_led_pin: "GPIO13"

########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#

esphome:
  # this board has 2mb flash, but esphome assumes 1mb for the 8285 board id
  platformio_options:
    board_upload.flash_size: 2MB
    board_upload.maximum_size: 2097152

esp8266:
  board: esp8285
  restore_from_flash: true

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/athom-smart-plug-no-relay.yaml@main
  import_full_config: false


packages:
  base-config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/base-configuration.yaml]
    refresh: 1h
    
  network_config:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/common/network-wifi.yaml]
    refresh: 1h

  athom-power-sensors:
    url: https://github.com/roving-ronin/myhomeassistant
    ref: main
    files: [esphome/sensors/athom-power-plug-no-relay.yaml]
    refresh: 1h

#  base-config:         !include common/base-configuration.yaml
#  wifi-config:         !include common/network-wifi.yaml
#  athom-power-sensors: !include sensors/athom-power-plug-no-relay.yaml

#####################################################################
#
# Define the COMs Port
#

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

#####################################################################
