#########################################################################
#
# Environmental monitoring using ESP32-S3 chipset and BME280 sensor(s)
# for temperature, humidity, pressure & dew point.
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name  
  name: "environmental-monitor"
   # Default friendly name 
  friendly_name: "Environmental Monitor"
   # Description as appears in ESPHome & top of webserver page
  device_description: "DIY - Environmental Monitor (Temp./Humidity/Pressure)"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc    
  location: ""  
   # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "TBC"  
   # Project Name
  project_name: "ESPHome DIY.Environmental Monitor v1"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "1.0.1"

  # If true, entity should not be added to Home Assistant frontend, without the user manually enabling it.
  disable_by_default: "false"

  # I2C PINS - Used for BME280 sensor
  sda_pin: GPIO20   # Default on ESP32 is SDA = PIN 21. ES32-S3 use 20
  scl_pin: GPIO21   # Default on ESP32 is SLC = PIN 22. ES32-S3 use 21

########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device. 
# Must be in the local devices configuration file.
#

#esp32:
#  board: esp32-s3-devkitc-1
#  framework:
#    type: arduino

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/diy-environmental-monitoring-v1.yaml@main
  import_full_config: false

packages:
  base-config:    !include common/base-configuration.yaml
  wifi-config:    !include common/network-wifi.yaml
  bme280-sensors: !include common/sensor-bme280.yaml
  esp-board:      !include boards/esp32-s3.yaml

#########################################################################
