#########################################################################
#
# Environmental monitoring using ESP32 chipset and BME280 sensor
# for temperature, humidity, pressure, dew point.
#

   # Provides substitutions or variables that are then called elsewhere multiple times in the config
substitutions:
   # Default name  
  name: "environ-monitor"
   # Default friendly name 
  friendly_name: "Environmental Monitor"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  device_description: "DIY - Environmental Monitor (Temp./Humidity/Pressure/Gas)"
   # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc      
  project_name: "ESPHome DIY.Environmental Monitor v1"
   # Project version denotes the release version of the yaml file, allowing checking of deployed vs latest version  
  project_version: "1.0.1"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO 1 = Phase C, GPO 2 = Phase A, GPO 3 = Phase B)
  power_circuit: "TBC"  

  # I2C PINS - Used for BME280 sensor
  sda_pin: GPIO20   # Default on ESP32 is SDA = PIN 21. ES32 S3 use 20
  scl_pin: GPIO21   # Default on ESP32 is SLC = PIN 22. ES32 S3 use 21

########################## End of Substitutions #########################
#
# Defines the type of ESP chip used on the device
#

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

#########################################################################
#
# Remote Packages to be utilised
#

dashboard_import:
  package_import_url: github://roving-ronin/myhomeassistant/esphome/diy-environmental-monitoring.yaml@main
  import_full_config: false

packages:
  base-config:    !include common/base-configuration.yaml
  wifi-config:    !include common/network-wifi.yaml
  bme280-sensors: !include common/sensor-bme280.yaml

#########################################################################
#
# Configure the onboard RGB LED of the 
#

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812x
    pin: 48
    num_leds: 1
    name: "Onboard RGB LED"
    id: onboard_led
    effects:
      - strobe:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

#########################################################################
