substitutions:
  name: "gpo-ups-server"
  friendly_name: "UPS - Servers"
  device_description: "Athom Plug v2 - Phase C / GPO 1 - Servers & NAS"
  # Allows ESP device to be automatically lined to an 'Area' in Home Assistant. Typically used for areas such as 'Lounge Room', 'Kitchen' etc
  room: "Network Rack"
  # The phase in the home power supply, upon which this plug is utilsed. 1p = A. 3p = A, B or C.  (myHome GPO1 = Phase C, GPO2 = Phase A, GPO3 = Phase B)
  power_circuit: "GPO 2"  
  relay_restore_mode: ALWAYS_ON  

esphome:
  name: "${name}"
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/Roving-Ronin/myHomeAssistant/
    ref: main 
    files: [esphome/athom-smart-plug-v2.yaml]
    refresh: 0d # optional
#  baseline: !include common/common_athom_plug_v2.yaml
