substitutions:
  device_name: "gpo-freezer"
  alias_name: "Freezer"
  device_description: "Measure the energy consumption of the Freezer"
  set_timezone: "Australia/Sydney"
  set_dns_domain: ".iot.home.lan"
  project_name: "athom.smart-plug-v2"
  project_version: "1.1 (Mod)"
  relay_restore_mode: RESTORE_DEFAULT_ON

esphome:
  name: "${device_name}"
  friendly_name: "${alias_name}"
  comment: '${device_description}'
  name_add_mac_suffix: false
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  baseline: !include common/common_athom_plug_v2.yaml

api:

ota:
  - platform: esphome

logger:
  level: WARN
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

wifi:
  # WiFi credentials
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: "${set_dns_domain}"
  fast_connect: true
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:
